# Generated by Django 3.0.4 on 2020-04-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tables',
            table='Operators',
        ),
    ]
