# Generated by Django 3.0.4 on 2020-04-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20200401_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='id',
            new_name='operators',
        ),
    ]
