# Generated by Django 3.0.4 on 2020-04-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20200401_0326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tables',
            new_name='Operators',
        ),
    ]
