# Generated by Django 3.0.4 on 2020-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20200401_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='operators',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
