# Generated by Django 3.0.4 on 2020-04-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20200402_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='admin',
            field=models.BooleanField(db_column='admin', default=0),
        ),
    ]
