# Generated by Django 3.0.4 on 2020-04-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_operators_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('bus_route', models.CharField(blank=True, db_column='Bus_Route', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bus_route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CallerNamePhoneOrg',
            fields=[
                ('id', models.FloatField(db_column='ID', primary_key=True, serialize=False)),
                ('caller_name', models.CharField(blank=True, db_column='Caller_Name', max_length=255, null=True)),
                ('phone_numbers', models.CharField(blank=True, db_column='Phone_Numbers', max_length=255, null=True)),
                ('caller_organization', models.CharField(blank=True, db_column='Caller_Organization', max_length=255, null=True)),
                ('f5', models.CharField(blank=True, db_column='F5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'caller_name_phone_org',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionGeneralEvent',
            fields=[
                ('id', models.FloatField(db_column='ID', primary_key=True, serialize=False)),
                ('construction_type', models.CharField(blank=True, db_column='Construction_Type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'construction_general_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionZoneAction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=50, null=True)),
            ],
            options={
                'db_table': 'construction_zone_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrossStreet',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cross_street', models.CharField(blank=True, db_column='Cross_Street', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cross_street',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Debris',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('debris', models.CharField(blank=True, db_column='Debris', max_length=50, null=True)),
            ],
            options={
                'db_table': 'debris',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetectionMethod',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('detectionmethod', models.CharField(blank=True, db_column='DetectionMethod', max_length=255, null=True)),
            ],
            options={
                'db_table': 'detection_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=50, null=True)),
            ],
            options={
                'db_table': 'direction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DmsList',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cctv_dms_names', models.CharField(blank=True, db_column='cctv_dms_names', max_length=255, null=True)),
                ('affectedtype', models.CharField(blank=True, db_column='AffectedType', max_length=255, null=True)),
                ('affectedtypeindex', models.IntegerField(blank=True, db_column='AffectedTypeIndex', null=True)),
                ('owningag', models.CharField(blank=True, db_column='OwningAg', max_length=255, null=True)),
                ('orderindex', models.IntegerField(blank=True, db_column='orderIndex', null=True)),
            ],
            options={
                'db_table': 'dms_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmergencyAction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=50, null=True)),
            ],
            options={
                'db_table': 'emergency_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipmentName',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cctv_dms_names', models.CharField(blank=True, db_column='cctv_dms_names', max_length=255, null=True)),
                ('affectedtype', models.CharField(blank=True, db_column='AffectedType', max_length=255, null=True)),
                ('affectedtypeindex', models.IntegerField(blank=True, db_column='AffectedTypeIndex', null=True)),
                ('owningag', models.CharField(blank=True, db_column='OwningAg', max_length=255, null=True)),
                ('orderindex', models.IntegerField(blank=True, db_column='orderIndex', null=True)),
            ],
            options={
                'db_table': 'equipment_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('equipment_system', models.CharField(blank=True, db_column='Equipment_System', max_length=255, null=True)),
                ('sorder', models.IntegerField(blank=True, db_column='SOrder', null=True)),
            ],
            options={
                'db_table': 'equipment_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeOfProblem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_problem', models.CharField(blank=True, db_column='type_of_problem', max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipment_type_of_problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneralEvent',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('gen_event', models.CharField(blank=True, db_column='Gen_Event', max_length=50, null=True)),
            ],
            options={
                'db_table': 'general_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpActionTaken',
            fields=[
                ('actiontaken', models.CharField(db_column='ActionTaken', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'help_action_taken',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpAssistType',
            fields=[
                ('typeofasssist', models.CharField(db_column='TypeOfAsssist', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'help_assist_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpHowNotified',
            fields=[
                ('hownotified', models.CharField(db_column='HowNotified', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'help_how_notified',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('municipality', models.CharField(blank=True, db_column='Municipality', max_length=255, null=True)),
                ('active', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NittecEmployee',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=50, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True)),
                ('isadmin', models.TextField(blank=True, db_column='isAdmin', null=True)),
            ],
            options={
                'db_table': 'nittec_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NonEmergencyAction',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=50, null=True)),
            ],
            options={
                'db_table': 'non_emergency_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OwningAgency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_agency', models.CharField(blank=True, db_column='Member_Agency', max_length=50, null=True)),
            ],
            options={
                'db_table': 'owning_agency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('phone_number', models.CharField(db_column='phone_number', max_length=50, primary_key=True, serialize=False)),
                ('orderindex', models.IntegerField(blank=True, db_column='orderIndex', null=True)),
            ],
            options={
                'db_table': 'phonenumber',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PvmsList',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nittec_name_crossroads_description', models.CharField(blank=True, db_column='NITTEC_NAME_CROSSROADS_DESCRIPTION', max_length=255, null=True)),
                ('owner_id', models.CharField(blank=True, db_column='OWNER_ID', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=255, null=True)),
                ('project_id_description', models.CharField(blank=True, db_column='PROJECT_ID_DESCRIPTION', max_length=255, null=True)),
                ('active', models.TextField(blank=True, db_column='ACTIVE', null=True)),
                ('show', models.TextField(blank=True, db_column='SHOW', null=True)),
                ('rowxcol', models.CharField(blank=True, db_column='ROWXCOL', max_length=255, null=True)),
                ('comp', models.CharField(blank=True, db_column='COMP', max_length=255, null=True)),
                ('software', models.CharField(blank=True, db_column='SOFTWARE', max_length=255, null=True)),
                ('user_password', models.CharField(blank=True, db_column='USER_PASSWORD', max_length=255, null=True)),
                ('field_status', models.CharField(blank=True, db_column='FIELD_STATUS', max_length=255, null=True)),
                ('owner', models.CharField(blank=True, db_column='OWNER', max_length=255, null=True)),
                ('make', models.CharField(blank=True, db_column='MAKE', max_length=255, null=True)),
                ('phase1line1', models.CharField(blank=True, db_column='PHASE1LINE1', max_length=255, null=True)),
                ('phase1line2', models.CharField(blank=True, db_column='PHASE1LINE2', max_length=255, null=True)),
                ('phase1line3', models.CharField(blank=True, db_column='PHASE1LINE3', max_length=255, null=True)),
                ('phase2line1', models.CharField(blank=True, db_column='PHASE2LINE1', max_length=255, null=True)),
                ('phase2line2', models.CharField(blank=True, db_column='PHASE2LINE2', max_length=255, null=True)),
                ('phase2line3', models.CharField(blank=True, db_column='PHASE2LINE3', max_length=255, null=True)),
                ('controller_address', models.FloatField(blank=True, db_column='CONTROLLER_ADDRESS', null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PHONE_NUMBER', max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, db_column='IP_ADDRESS', max_length=255, null=True)),
                ('public_name', models.CharField(blank=True, db_column='PUBLIC_NAME', max_length=255, null=True)),
                ('public_description', models.CharField(blank=True, db_column='PUBLIC_DESCRIPTION', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=255, null=True)),
                ('match', models.CharField(blank=True, db_column='Match', max_length=50, null=True)),
                ('crossroads_driven', models.TextField(blank=True, db_column='CROSSROADS_DRIVEN', null=True)),
            ],
            options={
                'db_table': 'pvms_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportingMemberAgency',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('reporting_member_agency', models.CharField(blank=True, db_column='Reporting_Member_Agency', max_length=255, null=True)),
            ],
            options={
                'db_table': 'reporting_member_agency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportingName',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('reporting_name', models.CharField(blank=True, db_column='Reporting_Name', max_length=255, null=True)),
                ('active', models.TextField(blank=True, null=True)),
                ('orderindex', models.IntegerField(blank=True, db_column='orderIndex', null=True)),
            ],
            options={
                'db_table': 'reporting_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RouteStreet',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('route_street', models.CharField(blank=True, db_column='Route_Street', max_length=255, null=True)),
            ],
            options={
                'db_table': 'route_street',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('signal_problems', models.CharField(blank=True, db_column='signal_problems', max_length=50, null=True)),
            ],
            options={
                'db_table': 'signal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransitOperatorResponse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operator_response', models.CharField(blank=True, db_column='Operator_Response', max_length=50, null=True)),
            ],
            options={
                'db_table': 'transit_operator_response',
                'managed': True,
            },
        ),
    ]
