# Generated by Django 3.0.4 on 2020-04-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_busroute_callernamephoneorg_constructiongeneralevent_constructionzoneaction_crossstreet_debris_detec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
