# Generated by Django 3.0.4 on 2020-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20200402_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nittecemployee',
            name='isadmin',
            field=models.NullBooleanField(db_column='isAdmin'),
        ),
    ]
