# Generated by Django 3.0.4 on 2020-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20200402_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmslist',
            name='active',
            field=models.NullBooleanField(db_column='ACTIVE'),
        ),
        migrations.AlterField(
            model_name='pvmslist',
            name='crossroads_driven',
            field=models.NullBooleanField(db_column='CROSSROADS_DRIVEN'),
        ),
        migrations.AlterField(
            model_name='pvmslist',
            name='show',
            field=models.NullBooleanField(db_column='SHOW'),
        ),
    ]
