# Generated by Django 2.2.5 on 2020-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_construction_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('route_street', models.CharField(max_length=50)),
                ('general_event', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='open_equipment_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('equiupment_system', models.CharField(max_length=20)),
                ('equipment_name', models.CharField(max_length=20)),
                ('type_of_problem', models.CharField(max_length=20)),
                ('owning_agency', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='open_event_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('route_street', models.CharField(max_length=50)),
                ('general_event', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ACL',
        ),
    ]
