# Generated by Django 3.0.4 on 2020-04-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageClaimsLog',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, db_column='zip', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_Number', max_length=50, null=True)),
                ('nysdot_claims', models.NullBooleanField(db_column='NYSDOT_Claims')),
                ('erie_county', models.NullBooleanField(db_column='Erie_County')),
                ('nysta', models.NullBooleanField(db_column='NYSTA')),
                ('other', models.CharField(blank=True, db_column='Other', max_length=50, null=True)),
                ('operators', models.CharField(blank=True, db_column='Operators', max_length=50, null=True)),
                ('vehicle_infomation', models.TextField(blank=True, db_column='vehicle_infomation', null=True)),
                ('information_box', models.TextField(blank=True, db_column='Information_box', null=True)),
                ('damageclaims_information', models.IntegerField(blank=True, db_column='DamageClaims_Information', null=True)),
                ('lockedID', models.NullBooleanField(db_column='lockedID')),
                ('modtime', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
            ],
            options={
                'db_table': 'damage_claims_log',
                'managed': True,
            },
        ),
    ]
