# Generated by Django 3.0.4 on 2020-04-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('closed', models.NullBooleanField(db_column='Closed')),
                ('closedtime', models.DateTimeField(blank=True, db_column='ClosedTime', null=True)),
                ('lockedID', models.NullBooleanField(db_column='lockedID')),
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('operatorsresponse', models.TextField(blank=True, db_column='OperatorsResponse', null=True)),
                ('cross_street', models.CharField(blank=True, db_column='Cross_Street', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=50, null=True)),
                ('route_street', models.CharField(blank=True, db_column='Route_Street', max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, db_column='Municipality', max_length=50, null=True)),
                ('event_description', models.TextField(blank=True, db_column='Event_Description', null=True)),
                ('caller_organization', models.CharField(blank=True, db_column='Caller_Organization', max_length=50, null=True)),
                ('caller_phone_field', models.CharField(blank=True, db_column='Caller_Phone', max_length=50, null=True)),
                ('caller_name', models.CharField(blank=True, db_column='Caller_Name', max_length=50, null=True)),
                ('gen_event', models.CharField(blank=True, db_column='Gen_Event', max_length=50, null=True)),
                ('operators', models.CharField(blank=True, db_column='Operators', max_length=50, null=True)),
                ('Time', models.TimeField(blank=True, db_column='time', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('owning_agency', models.CharField(blank=True, db_column='Owning_Agency', max_length=50, null=True)),
                ('detectiontime', models.TimeField(blank=True, db_column='DetectionTime', null=True)),
                ('verifytime', models.TimeField(blank=True, db_column='VerifyTime', null=True)),
                ('scenearrtime', models.TimeField(blank=True, db_column='SceneArrTime', null=True)),
                ('lanblockcleartime', models.TimeField(blank=True, db_column='LanBlockClearTime', null=True)),
                ('cleartime', models.TimeField(blank=True, db_column='ClearTime', null=True)),
                ('scenedeparttime', models.TimeField(blank=True, db_column='SceneDepartTime', null=True)),
                ('retnormtime', models.TimeField(blank=True, db_column='RetNormTime', null=True)),
                ('cars_active', models.NullBooleanField(db_column='CARS_active')),
                ('cars_deactive', models.NullBooleanField(db_column='CARS_deactive')),
                ('modtime', models.DateTimeField(blank=True, db_column='ModTime', null=True)),
                ('fullroadclosure', models.NullBooleanField(db_column='FullRoadClosure')),
                ('dmsactivelist', models.TextField(blank=True, db_column='DMSActiveList', null=True)),
                ('transalert_act', models.NullBooleanField(db_column='TransAlert_Act')),
                ('transalert_deact', models.NullBooleanField(db_column='TransAlert_DeAct')),
                ('tcws', models.NullBooleanField(db_column='TCWS')),
                ('skyway', models.NullBooleanField(db_column='Skyway')),
                ('hicfsent', models.NullBooleanField(db_column='HICFSent')),
                ('crdms_act', models.NullBooleanField(db_column='CRDMS_Act')),
                ('crdms_deact', models.NullBooleanField(db_column='CRDMS_DeAct')),
                ('crfaxemail_act', models.NullBooleanField(db_column='CRFaxEmail_Act')),
                ('crfaxemail_deact', models.NullBooleanField(db_column='CRFaxEmail_DeAct')),
                ('crweb_act', models.NullBooleanField(db_column='CRWeb_Act')),
                ('crweb_deact', models.NullBooleanField(db_column='CRWeb_DeAct')),
                ('num_lanes_blocked', models.IntegerField(blank=True, db_column='Num_Lanes_Blocked', null=True)),
                ('hicffinalsent', models.NullBooleanField(db_column='HICFFinalSent')),
                ('secondaryincident', models.NullBooleanField(db_column='SecondaryIncident')),
                ('secondaryincidentlognum', models.CharField(blank=True, db_column='SecondaryIncidentLogNum', max_length=255, null=True)),
                ('incseverity', models.IntegerField(blank=True, db_column='IncSeverity', null=True)),
                ('creventid', models.CharField(blank=True, db_column='CREventID', max_length=255, null=True)),
                ('detectmethod', models.CharField(blank=True, db_column='DetectMethod', max_length=255, null=True)),
                ('pvmsactivelist', models.TextField(blank=True, db_column='PVMSActiveList', null=True)),
                ('skyway_deact', models.NullBooleanField(db_column='Skyway_DeAct')),
                ('tcws_deact', models.NullBooleanField(db_column='TCWS_DeAct')),
                ('priority_response', models.NullBooleanField(db_column='Priority_Response')),
            ],
            options={
                'db_table': 'incident_log',
                'managed': True,
            },
        ),
    ]
