# Generated by Django 3.0.4 on 2020-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20200408_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlog',
            name='helplogid',
            field=models.IntegerField(blank=True, db_column='HelpLogID', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='cleartime',
            field=models.DateTimeField(blank=True, db_column='ClearTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='detectiontime',
            field=models.DateTimeField(blank=True, db_column='DetectionTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='lanblockcleartime',
            field=models.DateTimeField(blank=True, db_column='LanBlockClearTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='retnormtime',
            field=models.DateTimeField(blank=True, db_column='RetNormTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='scenearrtime',
            field=models.DateTimeField(blank=True, db_column='SceneArrTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='scenedeparttime',
            field=models.DateTimeField(blank=True, db_column='SceneDepartTime', null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='verifytime',
            field=models.DateTimeField(blank=True, db_column='VerifyTime', null=True),
        ),
    ]
