# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20200412_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentlog',
            name='helplogid',
            field=models.IntegerField(blank=True, db_column='HelpLogID', null=True),
        ),
    ]
