# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-13 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20200408_2001'),
        ('incident', '0003_auto_20200412_2044'),
    ]

    operations = [
    ]
