# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-15 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_merge_20200413_1547'),
        ('incident', '0003_auto_20200413_1300'),
    ]

    operations = [
    ]
