# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnumber', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
